ALTER TABLE noteCours ADD COLUMN type VARCHAR(10) NOT NULL;
ALTER TABLE noteCours ADD COLUMN finalnote FLOAT NOT NULL;
ALTER TABLE noteCours ADD COLUMN score FLOAT NOT NULL;
ALTER TABLE noteCours DROP COLUMN  idn;

